import random
import json

import src.main.Block as block


def test_blocks():
    test_block_init()
    test_block_1()
    test_block_2()
    test_block_3()
    test_block_4()


def test_block_init():
    for i in range(10):
        block_index = random.randint(1, 10000)
        nonce_type = 1
        prev_hash = 'hash'
        host = random.randint(1, 3)
        new_block = block.Block(block_index, prev_hash, nonce_type, host)
        assert new_block is not None


def test_block_1():
    for i in range(10):
        block_index = random.randint(1, 10000)
        prev_hash = 'hash'
        nonce_type = 1
        host = random.randint(1, 3)
        new_block = block.create_new_block(block_index, prev_hash, nonce_type, host)
        assert new_block.index == block_index
        assert new_block.prev_hash == prev_hash
        assert new_block.index == block_index


def test_block_2():
    for i in range(10):
        prev_hash = 'hash'
        block_index = 1
        nonce_type = 1
        host = 1
        current_block = block.create_new_block(block_index, prev_hash, nonce_type, host)
        old_value_data = current_block.data
        old_value_length = len(current_block.data)
        new_value_length = random.randint(0, 255)
        current_block.generate_random_data(new_value_length)
        assert old_value_length != len(current_block.data)
        assert old_value_data != current_block.data
        assert len(current_block.data) == new_value_length


def test_block_3():
    for i in range(10):
        block_index = 1
        prev_hash = 'hash'
        nonce_type = 1
        host = 1
        current_block = block.create_new_block(block_index, prev_hash, nonce_type, host)
        assert type(current_block.hash) == str
        assert current_block.hash[-4:] == "0000"
        assert current_block.prev_hash == 'hash'


def test_block_4():
    for i in range(10):
        block_index = random.randint(1, 10000)
        prev_hash = 'somthing'
        nonce_type = random.randint(1, 3)
        host = random.randint(1, 3)
        new_block = block.create_new_block(block_index, prev_hash, nonce_type, host)
        json_block = new_block.block_to_json()
        assert type(json_block) == str
        python_object = json.loads(json_block)
        index = int(python_object['index'])
        cur_hash = python_object['hash']
        prev_hash = python_object['prev_hash']
        data = python_object['data']
        nonce = int(python_object['nonce'])
        assert index == new_block.index
        assert cur_hash == new_block.hash
        assert prev_hash == new_block.prev_hash
        assert data == new_block.data
        assert nonce == new_block.nonce

        genesis_block = block.create_genesis()
        python_object = json.loads(genesis_block)
        genesis_generated_by = python_object['This block generated by Node '][0]
        genesis_index = int(python_object['index'])
        genesis_hash = python_object['hash']
        genesis_prev_hash = python_object['prev_hash']
        genesis_data = python_object['data']
        assert genesis_generated_by == -1
        assert genesis_index == 0
        assert genesis_hash[-4:] == "0000"
        assert genesis_prev_hash == 'GENESIS'
        assert len(genesis_data) == 256
