import json


class Node:

    list_block = []

    def __init__(self, host):
        self.host = host
        self.block_index = None

    def block_handler(self, received_block):
        if int(json.loads(received_block)['index']) == 0:
            self.list_block.append(received_block)
            self.block_index = 0
            print(block_to_string(json.loads(received_block)))
            return True
        if int(json.loads(received_block)['index']) > json.loads(self.list_block[-1])['index']:
            self.list_block.append(received_block)
            self.block_index = int(json.loads(received_block)['index'])
            print(block_to_string(json.loads(received_block)))
            return True
        return False


def block_to_string(json_block):
    index = int(json_block['index'])
    current_hash = json_block['hash']
    prev_hash = json_block['prev_hash']
    data = json_block['data']
    nonce = int(json_block['nonce'])
    gen_num = json_block['This block generated by Node '][0]
    block_string = f'This block generated by Node [{gen_num}]: Index = {index}, Hash = {current_hash}, ' \
                   f'Prev_Hash = {prev_hash}, Data = {data}, Nonce = {nonce}'
    return block_string
